title: chem-bla-ics
name: Egon Willighagen
description:
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://egonw.github.io" # the base hostname & protocol for your site, e.g. http://example.com
mastodon:
  username: egonw
  instance: scholar.social
mastodon:
  username: egonw
  instance: akademienl.social

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll/mastodon_webfinger

minima:
  social-links:
    - { platform: github, user_url: "https://github.com/egonw" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=u8SjMZ0AAAAJ" }
    - { platform: orcid, user_url: "https://orcid.org/0000-0001-7542-0286" }
